library(ithir)
library(raster)
library(ipred)
library(nnet)
library(sp)
library(rasterVis)
library(C50)
library(randomForest)

hv.C5<- C5.0(x=DSM_data[training,c("AACN","Drainage.Index","Light.Insolation","TWI","Gamma.Total.Count")],y=DSM_data$terron[training],trials=1,rules=FALSE)
C.pred.hv.C5<- predict(hv.C5,newdata=DSM_data[training,])
V.pred.hv.C5<- predict(hv.C5,newdata=DSM_data[-training,])
goofcat(observed=DSM_data$terron[training],predicted=C.pred.hv.C5)
goofcat(observed=DSM_data$terron[-training],predicted=V.pred.hv.C5)
map.c5.C<- predict(covStack,hv.C5,type="class")
levelplot(map.c5.C,col.regions=area_colors)

#------------------------------------------------#
hv.RF<- randomForest(terron~AACN+Drainage.Index+Light.Insolation+TWI+Gamma.Total.Count,data=DSM_data[training,],ntree=500,mtry=5)
print(hv.RF)
importance(hv.RF)
predict(hv.RF,nredata=DSM_data[training,],type="response")
predict(hv.RF,nredata=DSM_data[training,],type="prob")
c.pred.hv.rf<- predict(hv.RF,newdata=DSM_data[training,])
goofcat(observed=DSM_data$terron[training],predicted=c.pred.hv.rf)
v.pred.hv.rf<- predict(hv.RF,newdata=DSM_data[-training,])
goofcat(observed=DSM_data$terron[-training],predicted=v.pred.hv.rf)
map.rf.c<- predict(covStack,hv.RF)
levelplot(map.rf.c,col.regions=area_colors)

